# Generated by Django 4.0.3 on 2022-06-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
