# Generated by Django 4.0.3 on 2022-06-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('SCIENCE', 'SCIENCE'), ('ART AND HUMANITY', 'ART AND HUMANITY'), ('COMMERCIAL', 'COMMERCIAL')], default='SCIENCE', max_length=20),
        ),
    ]
