# Generated by Django 4.0.3 on 2022-06-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_bio_profile_birth_date_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
